"""Generate the public-facing docs/RELIABILITY.md from stress_runner output.

The reliability table is the project's honest reliability surface:
per-protocol × per-model success rates, last_updated timestamps, and
any negative results published verbatim. The brief is: users should
make decisions on real data, not marketing claims.

Layout::

    # Research-OS reliability
    Last regenerated: 2026-06-05

    ## Per-project, per-model success rates
    | Project | Model | Success rate | Gates passed | Artifacts | Cost |
    |---|---|---|---|---|---|

    ## Per-protocol breakdown (across all projects + models)
    | Protocol | Runs | Success rate | Notes |
"""
from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from research_os.testing.stress_runner import StressResult


def write_reliability_md(
    results: list[StressResult], output_path: Path
) -> Path:
    """Render the table to `output_path` (typically `docs/RELIABILITY.md`)."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# Research-OS reliability",
        "",
        f"_Last regenerated: {now}_",
        "",
        "This file is auto-generated by the stress-test harness on every",
        "release. The numbers below are empirical: each reference project",
        "is replayed end-to-end against the listed models. Negative",
        "results are surfaced verbatim — if a model fails at a protocol,",
        "you'll see it here.",
        "",
        "## Per-project, per-model results",
        "",
        "| Project | Model | Success rate | Gates passed | Artifacts present | Duration | Tool calls |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in sorted(results, key=lambda x: (x.project_name, x.model_label)):
        gates_total = len(r.gates_passed) + len(r.gates_failed)
        arts_total = len(r.artifacts_present) + len(r.artifacts_missing)
        lines.append(
            "| {p} | {m} | {sr:.0%} | {g}/{gt} | {a}/{at} | {d:.1f}s | {tc} |".format(
                p=r.project_name,
                m=r.model_label,
                sr=r.success_rate,
                g=len(r.gates_passed),
                gt=max(gates_total, 1),
                a=len(r.artifacts_present),
                at=max(arts_total, 1),
                d=r.duration_seconds,
                tc=r.tool_calls,
            )
        )
    lines += [
        "",
        "## Per-protocol breakdown",
        "",
        "Each row = one protocol, aggregated across every project and model where it was attempted.",
        "",
        "| Protocol | Attempts | Successes | Success rate |",
        "|---|---|---|---|",
    ]
    proto_stats: dict[str, dict] = defaultdict(lambda: {"attempts": 0, "successes": 0})
    for r in results:
        for p in r.protocols_attempted:
            proto_stats[p]["attempts"] += 1
        for p in r.protocols_completed:
            proto_stats[p]["successes"] += 1
    for proto, stats in sorted(proto_stats.items()):
        attempts = stats["attempts"]
        succ = stats["successes"]
        rate = succ / max(attempts, 1)
        lines.append(
            f"| `{proto}` | {attempts} | {succ} | {rate:.0%} |"
        )

    # Surface notes (failure traces) verbatim.
    note_rows: list[tuple[str, str, str]] = []
    for r in results:
        for n in r.notes:
            note_rows.append((r.project_name, r.model_label, n))
    if note_rows:
        lines += [
            "",
            "## Notes (verbatim failure traces)",
            "",
            "| Project | Model | Note |",
            "|---|---|---|",
        ]
        for p, m, n in note_rows:
            lines.append(f"| {p} | {m} | {n} |")

    lines += [
        "",
        "## How to reproduce",
        "",
        "```bash",
        "# CI (mock model — deterministic; no API keys needed)",
        "python -m research_os.testing.stress_runner --model mock",
        "",
        "# Real-model runs (requires the corresponding adapter + API key)",
        "STRESS_MODEL=claude-sonnet-4-6 python -m research_os.testing.stress_runner --model anthropic",
        "```",
        "",
        "Adapter modules live under `src/research_os/testing/adapters/`.",
        "Reference projects live under `tests/fixtures/projects/`.",
        "",
    ]
    output_path.write_text("\n".join(lines))
    return output_path
