"""Humanities pack tools.

Tools are captured by the @register_tool decorator at import time;
the pack's `register()` function then pulls them via
`captured_tools(__name__)`.

Three tools:
    * tool_humanities_archive_lookup  — query Internet Archive / HathiTrust / DPLA / Europeana
    * tool_humanities_transcribe      — OCR + correction workflow for archival images
    * tool_humanities_citation_chain  — trace a quote through critical editions back to earliest extant source

These are scaffolds: they write structured plan files / templates the
researcher fills in. Heavy work (actual OCR, actual API calls when no
key is configured) is deferred to the researcher's scripts to keep
the pack free of network / OCR dependencies.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from research_os.plugins import (
    PackPathError,
    pack_err as _err,
    pack_ok as _ok,
    register_tool,
    resolve_in_root,
)


@register_tool(
    "tool_humanities_archive_lookup",
    schema={
        "type": "object",
        "properties": {
            "query": {"type": "string"},
            "archives": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Subset of: internet_archive, hathitrust, dpla, europeana, gallica, loc",
            },
            "max_per_archive": {"type": "integer"},
        },
        "required": ["query"],
    },
    description=(
        "Query digital archives (Internet Archive / HathiTrust / DPLA / "
        "Europeana / Gallica / Library of Congress) for primary sources. "
        "Writes a structured lookup plan to "
        "inputs/archival/lookup_<slug>.md with the search queries + "
        "API endpoints; the researcher executes the queries (some "
        "archives require API keys or session cookies)."
    ),
)
def archive_lookup(name: str, arguments: dict, root: Path) -> Any:
    query = (arguments.get("query") or "").strip()
    archives = arguments.get("archives") or [
        "internet_archive", "hathitrust", "dpla", "europeana",
    ]
    max_per = int(arguments.get("max_per_archive") or 10)
    out_dir = root / "inputs" / "archival"
    out_dir.mkdir(parents=True, exist_ok=True)
    slug = (
        query.lower()
        .replace(" ", "_")
        .replace("/", "_")
        .strip("_")[:60]
        or "query"
    )
    plan = out_dir / f"lookup_{slug}.md"

    endpoint_map = {
        "internet_archive":
            "https://archive.org/advancedsearch.php?q={q}&output=json",
        "hathitrust":
            "https://catalog.hathitrust.org/Search/Home?lookfor={q}&type=all&format=json",
        "dpla":
            "https://api.dp.la/v2/items?q={q}&api_key=<DPLA_KEY>",
        "europeana":
            "https://api.europeana.eu/record/v2/search.json?wskey=<EUROPEANA_KEY>&query={q}",
        "gallica":
            "https://gallica.bnf.fr/SRU?operation=searchRetrieve&query={q}&recordSchema=dc",
        "loc":
            "https://www.loc.gov/search/?q={q}&fo=json",
    }

    lines = [
        f"# Archival lookup plan — {query}",
        "",
        f"Generated by tool_humanities_archive_lookup (max_per_archive={max_per}).",
        "Each archive below has its own search syntax + auth model.",
        "Where an API key is required, set it in `inputs/researcher_config.yaml`",
        "under `api_keys:`. The researcher runs the queries below and",
        "lands the results back in `inputs/archival/results_<archive>.json`.",
        "",
    ]
    for arch in archives:
        if arch not in endpoint_map:
            lines.append(f"## {arch}\n\n_Unknown archive — skipped._\n")
            continue
        url = endpoint_map[arch].format(q=query.replace(" ", "+"))
        lines.append(f"## {arch}")
        lines.append("")
        lines.append(f"- Query: `{query}`")
        lines.append(f"- Endpoint: `{url}`")
        lines.append(
            f"- Save results to: `inputs/archival/results_{arch}.json`"
        )
        lines.append("- Cap: top {} records.".format(max_per))
        lines.append("")
    plan.write_text("\n".join(lines))
    return _ok({
        "plan_path": str(plan.relative_to(root)),
        "archives_planned": archives,
        "advice": (
            "Run the queries listed in the plan; save raw results back "
            "to inputs/archival/. The next step (archival_research) "
            "expects results_<archive>.json to exist."
        ),
    })


@register_tool(
    "tool_humanities_transcribe",
    schema={
        "type": "object",
        "properties": {
            "image_path": {
                "type": "string",
                "description": "Path under inputs/archival/ to the image (or directory of images).",
            },
            "engine": {
                "type": "string",
                "enum": ["tesseract", "manual", "claude_vision"],
                "description": "OCR engine to plan for. 'manual' = scaffolds a side-by-side template only.",
            },
            "language": {"type": "string"},
        },
        "required": ["image_path"],
    },
    description=(
        "Scaffold an OCR + manual-correction workflow for an archival "
        "image. Writes a side-by-side transcription template "
        "(workspace/transcriptions/<stem>.md) with a quality-bar "
        "checklist (line breaks preserved, doubtful readings bracketed, "
        "abbreviations expanded silently or marked, etc.). Heavy OCR "
        "deferred to the researcher's script (tesseract subprocess or "
        "Claude Vision call) — keeps the pack free of OCR deps."
    ),
)
def transcribe(name: str, arguments: dict, root: Path) -> Any:
    image_path = (arguments.get("image_path") or "").strip()
    engine = arguments.get("engine") or "manual"
    language = arguments.get("language") or "lat"
    if not image_path:
        return _err("image_path is required")
    try:
        img_abs = resolve_in_root(root, image_path)
    except PackPathError as exc:
        return _err(str(exc))
    if not img_abs.exists():
        # A missing source image is a user-actionable error (matches the
        # other four packs); don't claim success on a dangling reference.
        return _err(f"image_path '{image_path}' not found — drop the image first")
    out_dir = root / "workspace" / "transcriptions"
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = img_abs.stem
    template = out_dir / f"{stem}.md"

    lines = [
        f"# Transcription — {stem}",
        "",
        f"- **Source image:** `{image_path}`",
        f"- **Engine:** `{engine}`",
        f"- **Language hint:** `{language}`",
        "- **Editorial conventions used:** (Leiden? bracketed conjectures? expansion silently?)",
        "",
        "## Quality bar",
        "",
        "- [ ] Line breaks match the manuscript layout (`|` for line-end)",
        "- [ ] Doubtful readings in `[...]`; lacunae as `[...]` with note",
        "- [ ] Abbreviations expanded — mark expansion convention up-top",
        "- [ ] Foliation / pagination preserved",
        "- [ ] First-pass + corrected pass dated below",
        "",
        "## First-pass transcription",
        "",
        "```",
        "",
        "```",
        "",
        "## Corrected transcription",
        "",
        "```",
        "",
        "```",
        "",
        "## Editorial notes",
        "",
    ]
    template.write_text("\n".join(lines))
    return _ok({
        "template_path": str(template.relative_to(root)),
        "engine": engine,
        "next_steps": [
            "Run OCR (or transcribe by hand) into the First-pass block.",
            "Side-by-side compare with the image; correct in the Corrected block.",
            "Log editorial notes below.",
        ],
    })


@register_tool(
    "tool_humanities_citation_chain",
    schema={
        "type": "object",
        "properties": {
            "quotation": {"type": "string"},
            "attributed_to": {
                "type": "string",
                "description": "Name typically credited (e.g., 'Aristotle', 'Augustine')",
            },
            "earliest_known_source": {
                "type": "string",
                "description": "Earliest extant edition / manuscript you know of.",
            },
        },
        "required": ["quotation"],
    },
    description=(
        "Build a chain-of-custody for a quotation: original ms → critical "
        "edition → translation → secondary citation. Writes "
        "workspace/citations/chain_<slug>.md with a scaffold the "
        "researcher fills in, plus search hints for the missing links."
    ),
)
def citation_chain(name: str, arguments: dict, root: Path) -> Any:
    quote = (arguments.get("quotation") or "").strip()
    attributed = (arguments.get("attributed_to") or "Unknown").strip()
    earliest = arguments.get("earliest_known_source") or ""
    out_dir = root / "workspace" / "citations"
    out_dir.mkdir(parents=True, exist_ok=True)
    slug_seed = quote[:40] or "chain"
    slug = (
        slug_seed.lower()
        .replace(" ", "_")
        .replace("/", "_")
        .strip("_")[:50]
        or "chain"
    )
    chain_md = out_dir / f"chain_{slug}.md"

    lines = [
        f"# Citation chain — quotation attributed to {attributed}",
        "",
        f"> {quote}",
        "",
        f"- **Attributed to:** {attributed}",
        f"- **Earliest known source (your input):** {earliest or '_(unknown — fill in)_'}",
        "",
        "## Chain (most recent → earliest)",
        "",
        "1. **Secondary citation you read it in**: _(title, year, p.NN)_",
        "2. **English / target-language translation**: _(translator, edition, year, p.NN)_",
        "3. **Critical edition / scholarly edition**: _(editor, series, year, line ref)_",
        "4. **Manuscript / earliest extant source**: _(MS shelfmark, folio, century)_",
        "5. **Possible earlier (lost) source**: _(if applicable; describe the inference)_",
        "",
        "## Verification checklist",
        "",
        "- [ ] Each link in the chain is cited with a recoverable ref (no 'as quoted in X' loops)",
        "- [ ] The earliest extant source has been consulted directly (or marked 'consulted via critical edition')",
        "- [ ] Disputed attributions surfaced (e.g. 'often attributed to Aristotle but actually pseudo-Aristotelian')",
        "- [ ] Translation choices flagged where they bear on the argument",
        "",
        "## Search hints for missing links",
        "",
        "- Critical editions: `tool_search` source='crossref' query='" + quote[:80] + "'",
        "- Manuscripts: HMML reading room (medieval), TLG (classical Greek), CLCLT (Latin)",
        "- Translations: WorldCat for editions; jstor for translator commentary",
    ]
    chain_md.write_text("\n".join(lines))
    return _ok({
        "chain_path": str(chain_md.relative_to(root)),
        "advice": (
            "Fill in each link with a real, recoverable citation. "
            "'As quoted in' loops break the chain — track them down."
        ),
    })
