#!/usr/bin/env python3
"""Regenerate the "Full catalogue by category" section of docs/PROTOCOLS.md.

Reads every YAML under src/research_os/protocols/ (skipping _router_index
and _embeddings_*) and emits an alphabetised table per category with a
one-line description derived (in order of preference) from the protocol's
`summary`, first `description`, first step `description`, or `purpose`
field.

Idempotent — replaces the catalogue between the two HTML comment
sentinels `<!-- AUTO:PROTOCOL_CATALOGUE_START -->` and
`<!-- AUTO:PROTOCOL_CATALOGUE_END -->`. Exits 1 if the sentinels are
missing so CI catches the drift.

Run from the repo root::

    python scripts/regen_protocols_doc.py

See AUDIT-v1.9.2-010.
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
PROTOCOLS_DIR = REPO_ROOT / "src" / "research_os" / "protocols"
DOC_PATH = REPO_ROOT / "docs" / "PROTOCOLS.md"

START = "<!-- AUTO:PROTOCOL_CATALOGUE_START -->"
END = "<!-- AUTO:PROTOCOL_CATALOGUE_END -->"


def _first_nonempty_line(s: str) -> str:
    for ln in (s or "").splitlines():
        ln = ln.strip()
        if ln:
            return ln
    return ""


def _describe(data: dict) -> str:
    """Pull the best available one-line description from a protocol YAML."""
    for key in ("summary", "description", "purpose", "overview", "intent"):
        val = data.get(key)
        if isinstance(val, str) and val.strip():
            return _first_nonempty_line(val)
    # Fall back to the first step's description.
    steps = data.get("steps") or []
    if steps and isinstance(steps[0], dict):
        for key in ("description", "summary", "purpose"):
            val = steps[0].get(key)
            if isinstance(val, str) and val.strip():
                return _first_nonempty_line(val)
    return ""


def _shorten(s: str, width: int = 110) -> str:
    s = s.replace("|", "\\|")
    if len(s) <= width:
        return s
    return textwrap.shorten(s, width=width, placeholder="…")


def collect() -> dict[str, list[tuple[str, str]]]:
    out: dict[str, list[tuple[str, str]]] = {}
    for cat_dir in sorted(PROTOCOLS_DIR.iterdir()):
        if not cat_dir.is_dir():
            continue
        for path in sorted(cat_dir.glob("*.yaml")):
            if path.name.startswith("_"):
                continue
            try:
                data = yaml.safe_load(path.read_text()) or {}
            except Exception as e:  # pragma: no cover - parse errors are loud
                print(f"WARN: failed to parse {path}: {e}", file=sys.stderr)
                continue
            pid = data.get("id") or path.stem
            desc = _describe(data)
            out.setdefault(cat_dir.name, []).append((pid, desc))
    return out


def render(catalogue: dict[str, list[tuple[str, str]]]) -> str:
    total = sum(len(v) for v in catalogue.values())
    lines: list[str] = []
    lines.append("<!-- AUTO-GENERATED by scripts/regen_protocols_doc.py — DO NOT EDIT BY HAND -->")
    lines.append("")
    lines.append(f"_All {total} protocols, grouped by category, alphabetised within each._")
    lines.append("")
    for cat in sorted(catalogue):
        rows = sorted(catalogue[cat])
        lines.append(f"### `{cat}/` ({len(rows)} protocols)")
        lines.append("")
        lines.append("| Protocol | One-liner |")
        lines.append("|---|---|")
        for pid, desc in rows:
            lines.append(f"| `{pid}` | {_shorten(desc)} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    catalogue = collect()
    block = render(catalogue)

    text = DOC_PATH.read_text()
    if START not in text or END not in text:
        print(
            f"ERROR: PROTOCOLS.md missing sentinels {START!r} / {END!r}",
            file=sys.stderr,
        )
        return 1
    pre, _, rest = text.partition(START)
    _, _, post = rest.partition(END)
    new = pre + START + "\n" + block + END + post
    if new != text:
        DOC_PATH.write_text(new)
        print(f"Regenerated catalogue ({sum(len(v) for v in catalogue.values())} protocols).")
    else:
        print("No change.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
