graph LR
  %% Bootstrap roots
  bootstrap --> session_boot[session_boot]
  bootstrap --> session_resume[session_resume]
  %% next_protocol chain edges
  ablation_study --> analysis_plan
  analysis_plan --> reproducibility
  animation_design --> figure_critique
  archival_research --> close_reading
  audit_and_validation --> synthesis_paper
  autopilot --> analysis_plan
  bayesian_analysis --> analysis_plan
  bootstrapping_design --> uncertainty_quantification
  build_test_fix_loop --> test_failure_causation
  causal_inference_deep --> analysis_plan
  clinical_trials --> analysis_plan
  close_reading --> citation_chains
  coding_scheme_development --> inter_rater_reliability
  coding_scheme_iteration --> member_checking
  coq_integration --> proof_verification_workflow
  cox_ph_diagnostics --> audit_and_validation
  data_management_plan --> pre_submission_checklist
  data_quality_audit --> methodology_selection
  dead_end_routing --> analysis_plan
  deep_domain_research --> methodology_selection
  defense_prep --> synthesis_slides
  design_iteration --> requirements_traceability
  digital_humanities_workflow --> scholarly_edition
  distant_reading --> digital_humanities_workflow
  distribution_comparison --> figure_critique
  domain_analysis --> deep_domain_research
  evaluation_design --> methodology_selection
  evidence_synthesis --> analysis_plan
  exploratory_data_analysis --> methodology_selection
  external_tool_setup --> mcp_ecosystem_integration
  fairness_audit --> uncertainty_quantification
  fmea_protocol --> fault_tree_analysis
  geospatial_visualization --> figure_critique
  grounded_theory_iteration --> coding_scheme_iteration
  hermeneutic_method --> close_reading
  hyperparameter_search_design --> method_comparison
  inter_rater_reliability --> coding_scheme_development
  interactive_dashboard_design --> synthesis_dashboard
  interview_guide_design --> coding_scheme_development
  iterative_planning --> analysis_plan
  journal_selection --> synthesis_paper
  lean_integration --> proof_verification_workflow
  lemma_library --> theorem_dependency_graph
  literature_search --> analysis_plan
  machine_learning --> analysis_plan
  manuscript_outline --> synthesis_paper
  mcp_ecosystem_integration --> external_tool_setup
  member_checking --> qualitative_report_format
  meta_analysis --> analysis_plan
  method_comparison --> analysis_plan
  methodology_selection --> literature_search
  missing_data_strategy --> audit_and_validation
  mixed_language_orchestration --> analysis_plan
  mixed_methods --> analysis_plan
  multiple_comparisons --> preregistration
  network_visualization --> figure_critique
  peer_review_response --> analysis_plan
  pick_tool_stack --> analysis_plan
  pilot_study --> research_design
  plate_map_provenance --> instrument_run_log
  power_analysis --> preregistration
  preregistration --> analysis_plan
  project_startup --> domain_analysis
  proof_strategy_selection --> proof_verification_workflow
  proof_verification_workflow --> theory_paper_structure
  provenance_completeness --> audit_and_validation
  qualitative_quality_audit --> audit_and_validation
  qualitative_research --> analysis_plan
  reagent_lot_tracking --> wet_lab_reproducibility_audit
  replication_study --> analysis_plan
  reproducibility --> audit_and_validation
  requirements_traceability --> fmea_protocol
  research_design --> methodology_selection
  revise_and_resubmit --> pre_submission_checklist
  sample_lineage --> wet_lab_reproducibility_audit
  showcase_visualization --> figure_critique
  simulation_studies --> analysis_plan
  sop_versioning --> reagent_lot_tracking
  source_provenance --> scholarly_edition
  survey_design --> survey_psychometrics
  survey_psychometrics --> analysis_plan
  synthesis_null_findings --> synthesis_paper
  systematic_review --> evidence_synthesis
  thematic_analysis_braun_clarke --> member_checking
  timeseries_analysis --> analysis_plan
  tool_discovery --> methodology_selection
  uncertainty_quantification --> fairness_audit
  uncertainty_visualization --> uncertainty_quantification
  wet_lab_experiment_design --> plate_map_provenance
  wet_lab_reproducibility_audit --> methods_section_wet_lab
  writing_discussion --> writing_limitations
  writing_results --> writing_discussion
  %% Terminal protocols (next_protocol: null)
  casual_exploration -.-> END_TERM
  chat_handoff -.-> END_TERM
  citation_chains -.-> END_TERM
  code_review -.-> END_TERM
  collaboration_handoff -.-> END_TERM
  color_accessibility_audit -.-> END_TERM
  comparative_paper_review -.-> END_TERM
  conjecture_tracking -.-> END_TERM
  constructive_disagreement -.-> END_TERM
  data_ethics_review -.-> END_TERM
  engineering_report_structure -.-> END_TERM
  fault_tree_analysis -.-> END_TERM
  figure_critique -.-> END_TERM
  figure_guidelines -.-> END_TERM
  figure_narrative_arc -.-> END_TERM
  glossary_update -.-> END_TERM
  hypothesis_tracking -.-> END_TERM
  instrument_run_log -.-> END_TERM
  interactive_figure_design -.-> END_TERM
  literature_per_step -.-> END_TERM
  methodological_consultation -.-> END_TERM
  methods_section_wet_lab -.-> END_TERM
  mid_pipeline_entry -.-> END_TERM
  multi_panel_composition -.-> END_TERM
  pre_submission_checklist -.-> END_TERM
  printable -.-> END_TERM
  qualitative_report_format -.-> END_TERM
  quick_paper_review -.-> END_TERM
  reproduction_attempt -.-> END_TERM
  scholarly_edition -.-> END_TERM
  scope_clarification -.-> END_TERM
  session_boot -.-> END_TERM
  session_resume -.-> END_TERM
  synthesis_abstract -.-> END_TERM
  synthesis_cover_letter -.-> END_TERM
  synthesis_dashboard -.-> END_TERM
  synthesis_from_inputs -.-> END_TERM
  synthesis_grant -.-> END_TERM
  synthesis_lay_summary -.-> END_TERM
  synthesis_paper -.-> END_TERM
  synthesis_progress_update -.-> END_TERM
  synthesis_report -.-> END_TERM
  synthesis_slides -.-> END_TERM
  synthesis_title_workshop -.-> END_TERM
  test_failure_causation -.-> END_TERM
  theorem_dependency_graph -.-> END_TERM
  theory_paper_structure -.-> END_TERM
  visualization_workflow -.-> END_TERM
  writing_analysis_log -.-> END_TERM
  writing_citations -.-> END_TERM
  writing_conclusions -.-> END_TERM
  writing_core -.-> END_TERM
  writing_data_availability -.-> END_TERM
  writing_limitations -.-> END_TERM
  writing_methods -.-> END_TERM
  writing_readme -.-> END_TERM
  END_TERM[(end-of-chain)]
  %% Cycles detected
  %% Cycle 1: uncertainty_quantification <-> fairness_audit
  %% Cycle 2: coding_scheme_development <-> inter_rater_reliability
  %% Cycle 3: external_tool_setup <-> mcp_ecosystem_integration